set_property IOSTANDARD LVCMOS12 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports {GPIO_0_0_tri_io[1]}]
set_property DRIVE 8 [get_ports {GPIO_0_0_tri_io[0]}]
set_property DRIVE 8 [get_ports {GPIO_0_0_tri_io[1]}]
set_property PACKAGE_PIN C17 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN L14 [get_ports {GPIO_0_0_tri_io[1]}]
